INSERT INTO "humedales" (
    num_hum,
    nombre_hum,
    area_ha,
    perimetro,
    altitud,
    este,
    norte,
    longitud,
    latitud,
    fecha_act,
    cod_dane,
    municipio,
    departamen,
    vereda,
    ubicacion,
    jurisdicci,
    naturaleza,
    regimen_h,
    origen,
    tipo,
    instru_ges,
    uso,
    estado,
    nivel_inte,
    impactos,
    prioridad,
    accion,
    cuenca,
    descri_gen
) VALUES 
(
    'HUM-004',
    'Laguna Termal El Azufral',
    15.8,
    1420.5,
    2850.0,
    1064567.89,
    878754.67,
    -76.8756,
    2.7890,
    '2025-05-10',
    19001.0,
    'Coconuco',
    'Cauca',
    'El Azufral',
    'Rural'::"Ubicacion",
    'CRC',
    'Lentico'::"Naturaleza",
    'Permanente'::"Regimen",
    'Natural'::"Origen",
    'GeotermicoOTermal'::"Tipo",
    'Plan de Manejo Ambiental',
    ARRAY['Paisajistico'::"Uso", 'InteresAmbiental'::"Uso"],
    'Alta'::"Estado",
    'Baja'::"Nivel",
    ARRAY['ConflictosSociales'::"Impacto", 'Cultivos'::"Impacto"],
    'Alta'::"Prioridad",
    'Conservacion'::"Accion",
    'Río Cauca',
    'Humedal termal con importancia ecosistémica'
),
(
    'HUM-005',
    'Madrevieja Río Páez',
    23.4,
    1850.6,
    1250.0,
    1065678.90,
    879865.78,
    -76.9867,
    2.8901,
    '2025-05-12',
    19001.0,
    'Inzá',
    'Cauca',
    'La Vega',
    'Rural'::"Ubicacion",
    'CRC',
    'Lentico'::"Naturaleza",
    'Temporal'::"Regimen",
    'Natural'::"Origen",
    'Madrevieja'::"Tipo",
    'POMCA',
    ARRAY['Piscicultura'::"Uso", 'Reservorio'::"Uso"],
    'Media'::"Estado",
    'Media'::"Nivel",
    ARRAY['ModificacionDeCursosDeAgua'::"Impacto", 'PastoreoDeGanado'::"Impacto"],
    'Media'::"Prioridad",
    'Aislamiento'::"Accion",
    'Río Páez',
    'Antigua madrevieja con potencial productivo'
),
(
    'HUM-006',
    'Nacimiento La Sierpe',
    5.2,
    750.4,
    2450.0,
    1066789.01,
    880976.89,
    -77.0978,
    2.9012,
    '2025-05-15',
    19001.0,
    'Silvia',
    'Cauca',
    'La Sierpe',
    'Rural'::"Ubicacion",
    'CRC',
    'Lotico'::"Naturaleza",
    'Permanente'::"Regimen",
    'Natural'::"Origen",
    'Nacimiento'::"Tipo",
    'Plan de Restauración',
    ARRAY['Conservacion'::"Uso", 'Industrial'::"Uso"],
    'Baja'::"Estado",
    'Alta'::"Nivel",
    ARRAY['Desecamiento'::"Impacto", 'AlteracionDelSuelo'::"Impacto"],
    'Alta'::"Prioridad",
    'EducacionAmbiental'::"Accion",
    'Río Piendamó',
    'Nacimiento de agua con presión antrópica'
);